package com.cyecize.javache;

public enum JavacheConfigValue {

    MAX_REQUEST_SIZE,

    SHOW_REQUEST_LOG,

    WEB_APPS_DIR_NAME,

    ASSETS_DIR_NAME,

    APP_COMPILE_OUTPUT_DIR_NAME,

    MAIN_APP_JAR_NAME,

    APPLICATION_DEPENDENCIES_FOLDER_NAME,

    BROCOLLINA_SKIP_EXTRACTING_IF_FOLDER_EXISTS,

    BROCCOLINA_FORCE_OVERWRITE_FILES,

    BROCCOLINA_TRACK_RESOURCES,

    TOYOTE_MAX_NUMBER_OF_CACHED_FILES,

    TOYOYE_CACHED_FILE_MAX_SIZE,

    SERVER_PORT,

    SERVER_STARTUP_ARGS,

}
